/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.library;
import javax.swing.*;
import java.io.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Μαρία
 */
public class LibraryManagmentSystem_admin extends javax.swing.JFrame {
  


    /**
     * Creates new form LibraryManagmestSystem_admin
     */
    public LibraryManagmentSystem_admin() {
        initComponents();
         
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        books_database_admin = new javax.swing.JButton();
        view_users = new javax.swing.JButton();
        log_out = new javax.swing.JButton();
        insert_books = new javax.swing.JButton();
        update_books = new javax.swing.JButton();
        delete_books = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Library Managment System (Administrator)");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        books_database_admin.setBackground(new java.awt.Color(153, 0, 0));
        books_database_admin.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        books_database_admin.setForeground(new java.awt.Color(0, 0, 0));
        books_database_admin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Μαρία\\Documents\\SE-Library\\library\\src\\main\\java\\com\\mycompany\\library\\books_database.png")); // NOI18N
        books_database_admin.setText("View Books");
        books_database_admin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        books_database_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                books_database_adminMouseClicked(evt);
            }
        });
        books_database_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                books_database_adminActionPerformed(evt);
            }
        });
        jPanel1.add(books_database_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 190, 60));

        view_users.setBackground(new java.awt.Color(153, 0, 0));
        view_users.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        view_users.setForeground(new java.awt.Color(0, 0, 0));
        view_users.setIcon(new javax.swing.ImageIcon("C:\\Users\\Μαρία\\Documents\\SE-Library\\library\\src\\main\\java\\com\\mycompany\\library\\admin_database.png")); // NOI18N
        view_users.setText("View Users");
        view_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_usersMouseClicked(evt);
            }
        });
        view_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_usersActionPerformed(evt);
            }
        });
        jPanel1.add(view_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 190, 70));

        log_out.setBackground(new java.awt.Color(153, 0, 0));
        log_out.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        log_out.setForeground(new java.awt.Color(0, 0, 0));
        log_out.setIcon(new javax.swing.ImageIcon("C:\\Users\\Μαρία\\Documents\\SE-Library\\library\\src\\main\\java\\com\\mycompany\\library\\log_out.png")); // NOI18N
        log_out.setText("Log out");
        log_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log_outMouseClicked(evt);
            }
        });
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        jPanel1.add(log_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 190, 60));

        insert_books.setBackground(new java.awt.Color(153, 0, 0));
        insert_books.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        insert_books.setForeground(new java.awt.Color(0, 0, 0));
        insert_books.setIcon(new javax.swing.ImageIcon("C:\\Users\\Μαρία\\Documents\\SE-Library\\library\\src\\main\\java\\com\\mycompany\\library\\insert_book.png")); // NOI18N
        insert_books.setText("Insert Books");
        insert_books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insert_booksMouseClicked(evt);
            }
        });
        insert_books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_booksActionPerformed(evt);
            }
        });
        jPanel1.add(insert_books, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 190, 60));

        update_books.setBackground(new java.awt.Color(153, 0, 0));
        update_books.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        update_books.setForeground(new java.awt.Color(0, 0, 0));
        update_books.setIcon(new javax.swing.ImageIcon("C:\\Users\\Μαρία\\Documents\\SE-Library\\library\\src\\main\\java\\com\\mycompany\\library\\update.png")); // NOI18N
        update_books.setText("Update Books");
        update_books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_booksMouseClicked(evt);
            }
        });
        update_books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_booksActionPerformed(evt);
            }
        });
        jPanel1.add(update_books, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 190, 60));

        delete_books.setBackground(new java.awt.Color(153, 0, 0));
        delete_books.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        delete_books.setForeground(new java.awt.Color(0, 0, 0));
        delete_books.setIcon(new javax.swing.ImageIcon("C:\\Users\\Μαρία\\Documents\\SE-Library\\library\\src\\main\\java\\com\\mycompany\\library\\delete_book.png")); // NOI18N
        delete_books.setText("Delete Books");
        delete_books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_booksMouseClicked(evt);
            }
        });
        delete_books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_booksActionPerformed(evt);
            }
        });
        jPanel1.add(delete_books, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 190, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Library Managment System (Administrator)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 520, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("-");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 20, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Μαρία\\Documents\\SE-Library\\library\\src\\main\\java\\com\\mycompany\\library\\books.jpg")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(mainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        int result = JOptionPane.showConfirmDialog(null, "Do you want close this window?", "Confirmation", JOptionPane.YES_OPTION);
        if(result==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void delete_booksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_booksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_booksActionPerformed

    private void delete_booksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_booksMouseClicked
        // TODO add your handling code here:
        delete_books delete_books=new delete_books();
        delete_books.setVisible(true);
    }//GEN-LAST:event_delete_booksMouseClicked

    private void update_booksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_booksActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_update_booksActionPerformed

    private void update_booksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_booksMouseClicked
       update_books update_books=new update_books();
        update_books.setVisible(true);
    }//GEN-LAST:event_update_booksMouseClicked

    private void insert_booksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_booksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insert_booksActionPerformed

    private void insert_booksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insert_booksMouseClicked
        // TODO add your handling code here:
        insert_books insert_books=new insert_books();
        insert_books.setVisible(true);
    }//GEN-LAST:event_insert_booksMouseClicked

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        // TODO add your handling code here:
        JFrame frame=new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to Exit", "EXIT", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }

    }//GEN-LAST:event_log_outActionPerformed

    private void log_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_outMouseClicked

    }//GEN-LAST:event_log_outMouseClicked

    private void view_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_usersActionPerformed

    }//GEN-LAST:event_view_usersActionPerformed

    private void view_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_usersMouseClicked
        view_users view_users=new view_users();
        view_users.setVisible(true);

    }//GEN-LAST:event_view_usersMouseClicked

    private void books_database_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_books_database_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_books_database_adminActionPerformed

    private void books_database_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_books_database_adminMouseClicked
        // TODO add your handling code here:
        books_database_admin books_database_admin=new books_database_admin();
        books_database_admin.setVisible(true);

    }//GEN-LAST:event_books_database_adminMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        int result = JOptionPane.showConfirmDialog(null, "Do you want close this window?", "Confirmation", JOptionPane.YES_OPTION);
        if(result==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        int result = JOptionPane.showConfirmDialog(null, "Do you want close this window?", "Confirmation", JOptionPane.YES_OPTION);
        if(result==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

        int result = JOptionPane.showConfirmDialog(null, "Do you want close this window?", "Confirmation", JOptionPane.YES_OPTION);
        if(result==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryManagmentSystem_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryManagmentSystem_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryManagmentSystem_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryManagmentSystem_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryManagmentSystem_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton books_database_admin;
    private javax.swing.JButton delete_books;
    private javax.swing.JButton insert_books;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton log_out;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JButton update_books;
    private javax.swing.JButton view_users;
    // End of variables declaration//GEN-END:variables
}
