/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.library;

import javax.swing.JOptionPane;
import java.io.*;
import java.awt.*;
import java.sql.*;
import java.util.*;
import javax.swing.JFrame;

/**
 *
 * @author Μαρία
 */
public class update_books extends javax.swing.JFrame {

    /**
     * Creates new form update_books
     */
    public update_books() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        update_data_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        book_title = new javax.swing.JLabel();
        new_year_of_publication = new javax.swing.JLabel();
        New_Author = new javax.swing.JLabel();
        new_book_availability = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        txtnewyear = new javax.swing.JTextField();
        txt_New_Author_Book = new javax.swing.JTextField();
        txt_New_Book_Availability = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        update_data_button.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        update_data_button.setForeground(new java.awt.Color(0, 0, 0));
        update_data_button.setText("Update Data");
        update_data_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_data_buttonMouseClicked(evt);
            }
        });
        update_data_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_data_buttonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Μαρία\\Documents\\SE-Library\\library\\src\\main\\java\\com\\mycompany\\library\\update.png")); // NOI18N
        jLabel2.setText("Update Books");
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        book_title.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        book_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        book_title.setText("Title");

        new_year_of_publication.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        new_year_of_publication.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        new_year_of_publication.setText("New Year of Publication");

        New_Author.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        New_Author.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        New_Author.setText("New Author");

        new_book_availability.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        new_book_availability.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        new_book_availability.setText("New Book Availability");

        txtTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTitleFocusGained(evt);
            }
        });
        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });

        txtnewyear.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_New_Author_Book.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_New_Author_Book.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_New_Author_BookFocusGained(evt);
            }
        });
        txt_New_Author_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_New_Author_BookActionPerformed(evt);
            }
        });

        txt_New_Book_Availability.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_New_Book_Availability.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_New_Book_AvailabilityFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_New_Author_Book, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnewyear, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_New_Book_Availability, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(book_title, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(new_year_of_publication))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(New_Author, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(new_book_availability))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(update_data_button)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(34, 34, 34)
                .addComponent(book_title)
                .addGap(18, 18, 18)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(new_year_of_publication)
                .addGap(18, 18, 18)
                .addComponent(txtnewyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(New_Author)
                .addGap(18, 18, 18)
                .addComponent(txt_New_Author_Book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(new_book_availability)
                .addGap(18, 18, 18)
                .addComponent(txt_New_Book_Availability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(update_data_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void update_data_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_data_buttonMouseClicked
   
    }//GEN-LAST:event_update_data_buttonMouseClicked

    private void update_data_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_data_buttonActionPerformed
 int npy = 0;
    int newab = 0;
    String errorMessage = "";
    String newyeartext = txtnewyear.getText().trim();
    String newavailabilitybook = txt_New_Book_Availability.getText().trim();

    if (!newyeartext.isEmpty() && !newavailabilitybook.isEmpty()) {
        try {
            npy = Integer.parseInt(newyeartext);
            newab = Integer.parseInt(newavailabilitybook);
        } catch (NumberFormatException e) {
            errorMessage += "Invalid input for New Publish Year or New Book Availability. Please enter valid numbers.\n";
        }
    } else {
        errorMessage += "New Publish Year and New Book Availability must not be empty.\n";
    }

    if (txtTitle.getText().trim().isEmpty() || txt_New_Author_Book.getText().trim().isEmpty()) {
        errorMessage += "One or more fields are empty\n";
    }

    if (!errorMessage.isEmpty()) {
        JOptionPane.showMessageDialog(null, errorMessage);
        return; // Έξοδος από τη μέθοδο αν υπάρχει σφάλμα
    }

    // Το υπόλοιπο του κώδικα συνεχίζει εδώ
    String updateAuthorSql = "UPDATE book SET author = ? WHERE title = ?";
    String updatePubYearSql = "UPDATE book SET pub_year = ? WHERE title = ?";
    String updateAvailabilitySql = "UPDATE book SET available_books = ? WHERE title = ?";

    Connection myconnection = null;

    try {
        Class.forName("com.mysql.jdbc.Driver");
        String url = "jdbc:mysql://localhost/library";
        String user1 = "root";
        String password1 = "";
        myconnection = DriverManager.getConnection(url, user1, password1);

        if (myconnection != null) {
            System.out.println("Connected to the database library");

            String new_author = txt_New_Author_Book.getText().trim();
            String title = txtTitle.getText().trim();

            PreparedStatement updateAuthorStmt = myconnection.prepareStatement(updateAuthorSql);
            updateAuthorStmt.setString(1, new_author);
            updateAuthorStmt.setString(2, title);
            updateAuthorStmt.executeUpdate();

            PreparedStatement updatePubYearStmt = myconnection.prepareStatement(updatePubYearSql);
            updatePubYearStmt.setInt(1, npy);
            updatePubYearStmt.setString(2, title);
            updatePubYearStmt.executeUpdate();

            PreparedStatement updateAvailabilityStmt = myconnection.prepareStatement(updateAvailabilitySql);
            updateAvailabilityStmt.setInt(1, newab);
            updateAvailabilityStmt.setString(2, title);
            updateAvailabilityStmt.executeUpdate();

            JOptionPane.showMessageDialog(null, "Book information updated successfully!!");
        }
    } catch (Exception e) {
        System.out.print(e);
    } finally {
        if (myconnection != null) {
            try {
                myconnection.close();
            } catch (SQLException e) {
                System.out.println(e);
            }
        }
    }
    }//GEN-LAST:event_update_data_buttonActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        int result = JOptionPane.showConfirmDialog(null, "Do you want close this window?", "Confirmation", JOptionPane.YES_OPTION);
        if(result==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtTitleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTitleFocusGained
        txtTitle.setText("");
    }//GEN-LAST:event_txtTitleFocusGained

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void txt_New_Author_BookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_New_Author_BookFocusGained

        txt_New_Author_Book.setText("");
    }//GEN-LAST:event_txt_New_Author_BookFocusGained

    private void txt_New_Book_AvailabilityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_New_Book_AvailabilityFocusGained
        txt_New_Book_Availability.setText("");
    }//GEN-LAST:event_txt_New_Book_AvailabilityFocusGained

    private void txt_New_Author_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_New_Author_BookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_New_Author_BookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel New_Author;
    private javax.swing.JLabel book_title;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel new_book_availability;
    private javax.swing.JLabel new_year_of_publication;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txt_New_Author_Book;
    private javax.swing.JTextField txt_New_Book_Availability;
    private javax.swing.JTextField txtnewyear;
    private javax.swing.JButton update_data_button;
    // End of variables declaration//GEN-END:variables
}
